name: Release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  push:
    tags:
      - 'v*'

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.15.0
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.15.0
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18.15.0
      - name: install dependencies
        run: yarn install
      - name: publish
        env:
          ACCESS_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish
